version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:16e159331007eccc069822f7b731272043ed572a79a196a05ffa2ea127caaf67
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:693ed9f6e1d168c89309b103945466e93d58cd789ef233fcaa5dd1553ab9a9b0
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8080:8080'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:1817bb941c9a30fe2a6d75ff8675a8f6def408efe3d3ff43dbb006e2b534fa14
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4004:4004'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm i && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
