version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:0e3435e72c493aec752d8274379b1eac4d634f47a7781a7a92b8636fa1dc94c1
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:5f44b2f17a2b5361d19b75fdbfe5ffb4a90d175d55e1353a9974f2a900db8c6c
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8080:8080'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:0eafb338139eaaad6e867b22ef75dec1f7f51dcb08845531aed6cf6f6a1adea5
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4004:4004'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm i && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
