version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:b3a86578a582617214477d91e47e850f9e18df0b5d1644fb2d96d91a340b8972
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:868a2bccd2af479682544d250bf33b2e4d68f9c9c320b9bc6572d65c294464da
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8080:8080'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:bf1609ac718dda03940e2be4deae1704fb77cd6de2bed8bf91d4bbbc9e88b497
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4004:4004'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm i && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
