version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:1a73b6a8f507639a8f91ed01ace28965f4f74bb62a9d9b9e7378d5f07fab79dc
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:d1643d0ee498967273335faad43bfcbae1c777dc3ed6084de5cd3041ce756271
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8080:8080'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:ffe804d6fcced29bcfc3477de079d03a9c2b0e4917e44bfeafb1a6b0f875e383
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4004:4004'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm i && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
