# https://github.com/marketplace/actions/dependabot-auto-merge#inputs

name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          config: .github/auto-merge.yml # Path to configuration file (relative to root)
          github-token: ${{ secrets.GITHUB }}
          approve: true # Automatically approve pull-requests
